### ISSUE TITLE
Clean social media icons and links

### ISSUE THREAD

**Issue by vigliensoni** [sessions-marteau/sessions-marteau.github.io#2]
Remove icon and links not used or relevant (Youtube, Stackoverflow, Twitter) and those used (Mixcloud, Spotify, Instagram, and Facebook)

I tried a few things already in icomoon.svg, but the changes are not reflected on the rendered page.

**Comment by splouf** [comment]
I do believe it might be there to make the changes:
https://github.com/sessions-marteau/sessions-marteau.github.io/blob/master/_config.yml

**Comment by vigliensoni** [comment]
That is correct, you set the social handles, as well as all the site's configuration in the yaml file. However, the actual graphics of the social icons are stored in the file:

https://github.com/sessions-marteau/sessions-marteau.github.io/blob/master/assets/vendor/icomoon/icomoon.svg?short_path=e0cc1d0

But I have not been able to display them, yet.

Anyway, it is of low priority. I would prioritize content.

**Comment by splouf** [comment]
I really don't know how it does work it is probably linked to the template you have chosen has well... probably a custom template for our need would be best.

**Comment by vigliensoni** [comment]
Sure, but a custom template may require much more time and have a clear idea of the design beforehand.

**Comment by vigliensoni** [comment]
Not used social were cleaned. Now need to add used ones (Facebook, Instagram, and Podcast links)

@cordltx Perhaps having these links in the same row, but in a different class, that navigation tabs?
