### ISSUE TITLE
Lower the resolution of images

### ISSUE THREAD

**Issue by vigliensoni** [sessions-marteau/sessions-marteau.github.io#7]
The resolution of images in the repo is too high. We should resize them and lower their resolution to 72dpi.

**Comment by splouf** [comment]
I can do that were do I upload them?

**Comment by vigliensoni** [comment]
Images are on this same repository. Here is the link:

https://github.com/sessions-marteau/sessions-marteau.github.io/tree/master/uploads/session-001/pictures

**Comment by splouf** [comment]
maybe size as well ? do you know max pixel size they need to fit in?

**Comment by vigliensoni** [comment]
Perhaps 800px wide, 72dpi, JPG, compression 60.

**Comment by splouf** [comment]
let me know if it works at 72dpi
